SEARCH_API_NETLOC = 'www.gw.yad2.co.il/'
SEARCH_API_PATH_INITIAL = '/feed-search-legacy'
ITEM_API_BASE_URL = 'https://www.yad2.co.il/item/'
YAD2_NETLOC = 'www.yad2.co.il'
YAD2_DATETIME_STRING_FORMAT = '%Y-%m-%d %H:%M:%S'
